all:
  children:
    servers:
      vars:
        firewall_services:
          - http
          - ssh
        user_name: xitest
        ssh_public_keys:
          - "ssh-ed25519 AAAAC3NzaC1lZDI1NTE5AAAAIOH/TlOb8TAXiMhN8u7VNqPC7W2hrhygm/1BZBZZp0qo marek@GUADALAJARA-WSL"
          - "ssh-ed25519 AAAAC3NzaC1lZDI1NTE5AAAAIP7FHrfu37DbzYBs6T3P/aq+XOeJAtu8Ftl1/3g1EN/Ktkuba"
      hosts:
        192.168.100.23:
          ansible_user: vagrant
          ansible_ssh_private_key_file: ~/.ssh/id_rsa
          ansible_ssh_common_args: "-o StrictHostKeyChecking=no"
